name: token_store
version: 1.0.8
description: api for the dart pub token store.
repository: https://github.com/onepub-dev/token_store
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  cli_util: ^0.3.5
  dcli: ^1.34.0
  path: ^1.8.1
  stack_trace: ^1.10.0
dev_dependencies: 
  lints: ^2.0.0
  test: ^1.16.0
